# -*- coding: utf-8 -*-
"""EXEMPLO_ETL - DATA WAREHOUSE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JOe8YQO0Z6dvBFWymhFqyMkLYRTRaKnS
"""

import pandas as pd
import numpy as np

# Define a quantidadde como 600, e cria uma tabela Produtos.
num_produtos = 600
produtos = {
    'produto_id': range (1, num_produtos + 1),
    'nome': [f'Produto{i}' for i in range(1, num_produtos + 1)],
    'categoria': np.random.choice(['Eletrônicos', 'Roupas', 'Alimentos'], num_produtos)
}

# Converte a tabela de produtos em um DataFrame.
df_produtos = pd.DataFrame(produtos)

# Define a quantidade como 1000, e cria uma tabela de Vendas.
num_vendas = 1000 # Define a quantidade como 1000
data_vendas = {
    'data': np.random.choice(pd.date_range('2024-04-01', periods=30), num_vendas), # Contém uma lista de datas dentro do intervalo de 30 dias
    'produto_id': np.random.randint(1, num_produtos + 1, num_vendas),
    'quantidade': np.random.randint(50, 200, num_vendas), # Contém uma lista de quantidades entre 50 e 200
    'valor_total': np.random.randint(1000, 10000, num_vendas) # Contém uma lista de valores totais de vendas entre 1000 e 10000
}

# Converte a tabela de vendas em um DataFrame.
df_vendas = pd.DataFrame(data_vendas)

# Salvam os DataFrames em arquivos CSV
df_vendas.to_csv('vendas.csv', index=False)
df_produtos.to_csv('produtos.csv', index=False)

# Carregam os dados dos arquivos
df_vendas = pd.read_csv('vendas.csv')
df_produtos = pd.read_csv('produtos.csv')

# Junta os DataFrames df_vendas e df_produtos, usando uma junção interna (inner join).
df_merge = pd.merge(df_vendas, df_produtos, on='produto_id', how='inner')

# Salva o DataFrame em um arquivo CSV.
df_merge.to_csv('data_warehouse.csv', index=False)

# Carregam os dados dos arquivos em DataFrame
df_warehouse = pd.read_csv('data_warehouse.csv')
print ("Conteúdo do Data Warehouse:")
print (df_warehouse)

import pandas as pd
import matplotlib.pyplot as plt

# O código carrega os dados do arquivo 'data_warehouse.csv' em um DataFrame
df_warehouse = pd.read_csv('data_warehouse.csv')

# Agrupa os dados em df_warehouse pelo campo 'nome' (nome dos produtos). Calcula a soma das colunas 'quantidade' e 'valor_total' para cada grupo de produtos com o mesmo nome. O resultado é armazenado em vendas_por_produto, que é um resumo das vendas por produto.
vendas_por_produto = df_warehouse.groupby('nome')[['quantidade', 'valor_total']].sum()
print("Análise de vendas por produto:")
print(vendas_por_produto)

#Agrupa os dados em df_warehouse pelo campo 'categoria' (categoria dos produtos). Calcula a soma das colunas 'quantidade' e 'valor_total' para cada grupo de produtos com a mesma categoria. O resultado é armazenado em vendas_por_categoria, que é um resumo das vendas por categoria de produto.
vendas_por_categoria = df_warehouse.groupby('categoria')[['quantidade', 'valor_total']].sum()
print ("\nAnálise de vendas por categoria de produto:")
print (vendas_por_categoria)

# Primeiro, converte a coluna 'data' de df_warehouse para o formato de data e hora. Em seguida, agrupa os dados em df_warehouse pela data. Calcula a soma das colunas 'quantidade' e 'valor_total' para cada grupo de vendas com a mesma data. O resultado é armazenado em vendas_por_data, que é um resumo das vendas por data.
df_warehouse['data'] = pd.to_datetime(df_warehouse['data'])
vendas_por_data = df_warehouse.groupby('data')[['quantidade', 'valor_total']].sum()
print ("\nAnálise de tendências temporais:")
print (vendas_por_data)

# Cria um gráfico com um tamanho específico (10 por 5 polegadas). Plota uma linha com as datas (do índice de vendas_por_data) no eixo x e a quantidade vendida no eixo y. Define o título, rótulos dos eixos e adiciona uma grade ao gráfico. Mostra o gráfico plotado.
plt.figure(figsize=(10, 5))
plt.plot(vendas_por_data.index, vendas_por_data['quantidade'], marker='o', linestyle='-')
plt.title('Vendas ao longo do tempo')
plt.xlabel('Data')
plt.ylabel('Quantidade Vendida')
plt.grid(True)
plt.show()

# Agrupa os dados em df_warehouse pelo campo 'nome' (nome dos produtos). Calcula a soma da coluna 'valor_total' para cada grupo de produtos com o mesmo nome. O resultado é armazenado em desempenho_produto, que é um resumo do desempenho de cada produto em termos de valor total de vendas.
desempenho_produto = df_warehouse.groupby('nome')['valor_total'].sum()
print ("n\Análise de desempenho de produtos:")
print (desempenho_produto)