# -*- coding: utf-8 -*-
"""EXEMPLO_ETL - DATA WAREHOUSE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JOe8YQO0Z6dvBFWymhFqyMkLYRTRaKnS
"""

import pandas as pd
import numpy as np

# Define a quantidadde como 600, e cria uma tabela Produtos.
num_produtos = 600
produtos = {
    'produto_id': range (1, num_produtos + 1),
    'nome': [f'Produto{i}' for i in range(1, num_produtos + 1)],
    'categoria': np.random.choice(['Eletrônicos', 'Roupas', 'Alimentos'], num_produtos)
}

# Converte a tabela de produtos em um DataFrame.
df_produtos = pd.DataFrame(produtos)

# Define a quantidade como 1000, e cria uma tabela de Vendas.
num_vendas = 1000 # Define a quantidade como 1000
data_vendas = {
    'data': np.random.choice(pd.date_range('2024-04-01', periods=30), num_vendas), # Contém uma lista de datas dentro do intervalo de 30 dias
    'produto_id': np.random.randint(1, num_produtos + 1, num_vendas),
    'quantidade': np.random.randint(50, 200, num_vendas), # Contém uma lista de quantidades entre 50 e 200
    'valor_total': np.random.randint(1000, 10000, num_vendas) # Contém uma lista de valores totais de vendas entre 1000 e 10000
}

# Converte a tabela de vendas em um DataFrame.
df_vendas = pd.DataFrame(data_vendas)

# Salvam os DataFrames em arquivos CSV
df_vendas.to_csv('vendas.csv', index=False)
df_produtos.to_csv('produtos.csv', index=False)

# Carregam os dados dos arquivos
df_vendas = pd.read_csv('vendas.csv')
df_produtos = pd.read_csv('produtos.csv')

# Junta os DataFrames df_vendas e df_produtos, usando uma junção interna (inner join).
df_merge = pd.merge(df_vendas, df_produtos, on='produto_id', how='inner')

# Salva o DataFrame em um arquivo CSV.
df_merge.to_csv('data_warehouse.csv', index=False)

# Carregam os dados dos arquivos em DataFrame
df_warehouse = pd.read_csv('data_warehouse.csv')
print ("Conteúdo do Data Warehouse:")
print (df_warehouse)